os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v[0-9].*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: paULKPjyOJ56v3B7l1M7ZAHsJo5zGq9zW4Sos9Q+fUWZOEIkFiaKtecLWnY02b9OlV9L8ResF83UV7tCpy6TMpF8Vvk4Rj7b+uEB3R84tECNoAfyZaPEPhxdOY5wtC6pcRoBRhXQq9k7A9IDVYAtIKEa2JrXJja5tYbJzJXWSwAbA6IZRce60ZVYgAx2xEIy1+WzczvXFhu3hXZUtsWtOO23uXu+qEwdGYNqx0dE6jPkK4h1vY6MFIK82ePbtjpv+J7XvEoD12eJQF1s3dnU3QYlRbFKmuclcbs+UtC7ECgxt749tV8//x1DOgpsIOeLAhuVCszLyo5K7WnXQ2VsBri0bLEf9kU1KYL/9xsgRNyLM/oW4qTf6t4ZXRPEnVILyiFTVgHzshF/9wHHGBtO/DEexeMurDdaqEGlQkHILBaiepgTSEvq7dQ+8mRm2Ljz8lWXvvz8ggKTd2yII/3K97aWse0xK75hvW4JwWwrIrbyT3bEwUIqDXD4reHE3145xvbpMBcN472UB5O7pQGTGXU1dzTUgtCIBqQJy++73jcGVlhc35BhZABfwwh830Y/KJhom6UbsTP8IYR/VwJ9OfBd+t3YNcEK/l+hMY8FxfDCy9I4rW86pWj60LngoGKO2jPgyyzjRHXmJ7bCruqs17/YDWawkrLTs/JIeamN4s4=
  - secure: KGQZ+rRX5BYd4h2BBZILqmm3Tdru/o+C4HBQz0EvWTClgBD7vljJt/P1CKrLF93HTe4ihxCUIZ9qfOCb9I5SYfCSQxizK/ko4aVKQFgdjZq5pSZzYZTpB7FZ2wmdYZwC+OJTYnopHCgtTc3BcDuUeJJX5DwPXaMSdu/du6kUaAujd85j3YK/kc1Hhe/gGg1LVmd3ydeHwd8WBtsor0Lcf/53La0mpj6F5RYBO4IQ8z9LNNC7bz3w0Y6frs1g5IrZIeUYKp9hvuxQ6TKgOhjwOS61cme8RdgItQbRkfnWRPyrgEkppE29NKnrhHnM9DKry7MVhkttcnGYeV59Uh6eUXyeWqnxyFTVi3k7egPOIlKgu0I2RC42i1DQg0jPmiI7PjLSbrP6eCOQp5i0MEg9ayhjHOAZY9MOh3HRacvbQWjO47MfO68mdJDxv0wFB7h9mnTbMQCsB8/H6bmO1lrROMCE/jJYUAB0ceGKJvgbfzlCJ+ATNAKtOkbzOJjZbqdAuMRcVcwtcwZEHqeI3bhKUduTmnDiXRlpQ6VqHi+m+/K9tJjI9bfkHPfx6CkvCIhrbPyyadqCXSEP6wbDPHrbdAdomtPqYZOKNPPfG2KRs9UNMtlLGFkSq8PdE5uJqA5pNjrH24icDEgNpOnE5i6d1OS1G0JMYsbkl0kq2/gjae4=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE} .
script: skip
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- if [[ "${TRAVIS_BRANCH}" == *test* ]]; then docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER};
  docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}; echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}";
  else docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}; docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH};
  echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}"; fi
notifications:
  email:
    on_success: never
    on_failure: never
