os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v[0-9].*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: WyOFJdKz8fRJMiVNLH1Hsr7vORISHglnRSsXLTCZ5rIhzpfAWKzMu+uOTjLhMknSIQGObSPD5zq0o/NeWINX1+WVT9U7/DPBrPRMxfuDDrI2CBbA7MkqKlUdwH9asXSoyc7knSPxjg9XA457ysGkUfv0gXdea7UJ1IW5GV21b3Slp52ST6a03gk3iMqqxJa0n+fH3gkVoSRpOl3fiwivAfMFQvgHXXqaqKFXfUwtOq0gj5sEmv1nJmLVeYGLwSUQ66+G7s/Tylg7StZXvqGCTUbwdUhiyAWTPVg5rG/MFIpPonpMxlrHjpXG4OTMp5MwoMaWvBOeGefWVjriklatd4w9XbUDM9Z/kekW4UpMzLexCsWkk0BXaDUSFfQr0qLDN+JfVe899LjzuZE5ZHaRUoO5zf3SdDLtKxL6DSizJDU4pEXtGUMPphtD/hBfPXCmwn5z1uVqW25yt47rYBUnt3M8I/dYKbgxkewR+U5whcGyEs/Yrh8bvo42tdROoaTTiqF+zUr4pGm7HmcJE0nttJHLi2/tVjmBMEKKt3XjthyGnvv3CcXt7Oyi+xKLnZ7i+PgkWstMHLAEpi/Q18qmliTbuewvDS1MNCauDFOzLFnkWBgTHg5M4rvXan2fE7mPAcAstcwWgFwqdyCG6RcUiXO5Dgk4R1DZ9YIfv/I5wdc=
  - secure: WAXC/0Hsc8xHK+5kv5wEwG2yltxBWZvHrDrPmrok6/ZyDCGjuIQo0AmUypv7/uuMgDj1TueTkhSCEB1AQMzZAcRtwisoly10+qikDKiXe8xCbz/N+gwhun0Bx3wqm2wGY/uHL4or9ctgztnT70OORHRYPCSRG6ATiH34wee0tMTDF0QjLfdG211X8fEN9rROHmO0XQGpANh4MBPOiobr90bw5sc9Gc3xqcrairMm9NDOEzcGjWV4DeV5eM+swPRmVVW4yyrk3qzG1mrVkW4tGwF2nelo1GjWe++F91qNVDfXN33PIYL/YxceeiCCjXKLQv2WR/NTNTzLfw0yd5uUk7m2o3AAvEpYDYD5g+p00VkzIVAts4Pco/JdXGsI6WR3kEhk2vBzQnpAsdRRHqV0smTAqYKnVIw8QVmZPnjTLf0nIg2nntGDN4Mqmpsxp/EdlJbjBuhf2uojMWcVGlc4pYj9Y2GWdsyywY2V6B06i8AGv8YC53YWQru95nAeFGZBKermYfcqCaxmIC1cSDJ3MdmtfxmzGQFYL49g3b/pONrNI1vSdbSiFdb4zrk2T1/1fZbXcxxHetWktky80hygt7bHrGxiWagW++5/++LoyPjUWkJrXc+IH3VEqw9PTzAQReMkeHA5ifDCXiDvFvRvDzNxaVageCgwDcAZvCfqKM0=

install:
- docker build -f Dockerfile.amd64 -t ${IMAGE} .
script: skip
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- if [[ "${TRAVIS_BRANCH}" == *test* ]]; then docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER};
  docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}; echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}";
  else docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}; docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH};
  echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}"; fi
notifications:
  email:
    on_success: never
    on_failure: never
