version: '2'

services:
    state-machine:
        image: chalmersfsd/cfsd-logic-lynx-state-machine:test-delay13
        network_mode: "host"
        command: "state-machine --cid=219 --cidAnalog=219 --cidGpio=219 --cidPwm=219 --freq=2"