version: '2'

services:
    state-machine:
        image: chalmersfsd/state-machine:v0.0.0
        network_mode: "host"
        command: "state-machine --cid=219 --cidAnalog=219 --cidGpio=220 --cidPwm=222 --freq=2.0f --verbose=1"
